name: Flyway Migration

on:
  push:
    branches:
      - main

jobs:
  flyway-migrate:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flyway
        uses: red-gate/setup-flyway@v1

      - name: Run Flyway Migration
        run: flyway migrate -configFiles=conf/flyway-uat.toml
        env:
          FLYWAY_USER: ${{ secrets.FLYWAY_USER }}
          FLYWAY_PASSWORD: ${{ secrets.FLYWAY_PASSWORD }}